import '../app/global.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body><div className="bg-white w-screen h-screen text-black">{children}</div></body>
    </html>
  )
}
